<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_indeks extends CI_Model
{

    public $table = 'indeks_pegawai';
    public $id = 'ID_INDEKS';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        //$this->datatables->select('NIK,mstr_pegawai.NAMA_PEGAWAI,mstr_ruangan.DESCP_RUANGAN,mstr_level.DESCP_LEVEL,mstr_karir.DESC_KARIR,mstr_risiko_kerja.DESCP_RISIKO,mstr_ket_khusus.DESCP_KET,mstr_intensitas.DESCP_INTENSITAS,mstr_absensi.DESCP_ABSENSI,STATUS');
        $this->datatables->select('indeks_pegawai.NIK, mstr_pegawai.NAMA_PEGAWAI as NamaLengkap, mstr_level.DESCP_LEVEL as Jabatan, mstr_ruangan.DESCP_RUANGAN as NamaRuangan, mstr_karir.DESC_KARIR as JenjangKarir, mstr_risiko_kerja.DESCP_RISIKO as RisikoKerja, mstr_ket_khusus.DESCP_KET as KetKhusus, mstr_intensitas.DESCP_INTENSITAS as IntensitasPasien, mstr_absensi.DESCP_ABSENSI as Kehadiran, indeks_pegawai.STATUS');
        $this->datatables->from('indeks_pegawai');
        //add this line for join
        //$this->datatables->join('table2', 'det_indeks_pegawai.field = table2.field');
        $this->datatables->join('mstr_pegawai', 'indeks_pegawai.NIK = mstr_pegawai.NIK', 'LEFT');
        $this->datatables->join('mstr_level', 'indeks_pegawai.ID_LEVEL = mstr_level.ID_LEVEL', 'LEFT');
        $this->datatables->join('mstr_ruangan', 'indeks_pegawai.ID_RUANGAN = mstr_ruangan.ID_RUANGAN', 'LEFT');
        $this->datatables->join('mstr_karir', 'indeks_pegawai.ID_KARIR = mstr_karir.ID_KARIR', 'LEFT');
        $this->datatables->join('mstr_risiko_kerja', 'indeks_pegawai.ID_RISIKO = mstr_risiko_kerja.ID_RISIKO', 'LEFT');
        $this->datatables->join('mstr_ket_khusus', 'indeks_pegawai.ID_KET = mstr_ket_khusus.ID_KET', 'LEFT');
        $this->datatables->join('mstr_intensitas', 'indeks_pegawai.ID_INTENSITAS = mstr_intensitas.ID_INTENSITAS', 'LEFT');
        $this->datatables->join('mstr_absensi', 'indeks_pegawai.ID_ABSENSI = mstr_absensi.ID_ABSENSI', 'LEFT');
        $this->datatables->add_column('action', anchor(site_url('det_indeks/read/$1'),'Read')." | ".anchor(site_url('det_indeks/update/$1'),'Update')." | ".anchor(site_url('det_indeks/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), '');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ID_INDEKS', $q);
	$this->db->or_like('NIK', $q);
	$this->db->or_like('NAMA_PEGAWAI', $q);
	$this->db->or_like('DESCP_RUANGAN', $q);
	$this->db->or_like('DESCP_LEVEL', $q);
	$this->db->or_like('DESC_KARIR', $q);
	$this->db->or_like('DESCP_RISIKO', $q);
	$this->db->or_like('DESCP_KET', $q);
	$this->db->or_like('DESCP_INTENSITAS', $q);
	$this->db->or_like('DESCP_ABSENSI', $q);
  $this->db->or_like('STATUS', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID_INDEKS', $q);
	$this->db->or_like('NIK', $q);
	$this->db->or_like('NAMA_PEGAWAI', $q);
	$this->db->or_like('DESCP_RUANGAN', $q);
	$this->db->or_like('DESCP_LEVEL', $q);
	$this->db->or_like('DESC_KARIR', $q);
	$this->db->or_like('DESCP_RISIKO', $q);
	$this->db->or_like('DESCP_KET', $q);
	$this->db->or_like('DESCP_INTENSITAS', $q);
	$this->db->or_like('DESCP_ABSENSI', $q);
  $this->db->or_like('STATUS', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_indeks.php */
/* Location: ./application/models/M_indeks.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-30 05:14:04 */
/* http://harviacode.com */
