<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_pegawai extends CI_Model
{

    public $table = 'mstr_pegawai';
    public $id = 'ID_PEGAWAI';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
//        $this->datatables->select('ID_PEGAWAI,NIK,NAMA_PEGAWAI,ID_LEVEL,ID_RUANGAN,ID_KARIR,ID_RISIKO,ID_KET,ID_INTENSITAS,ID_ABSENSI,STATUS');
//        $this->datatables->from('mstr_pegawai');

          $this->datatables->select('mstr_pegawai.ID_PEGAWAI as ID_PEGAWAI, mstr_pegawai.NIK as NIK, mstr_pegawai.NAMA_PEGAWAI as NamaLengkap, mstr_level.DESCP_LEVEL as Jabatan,
                                    mstr_ruangan.DESCP_RUANGAN as NamaRuangan, mstr_karir.DESCP_KARIR as JenjangKarir, mstr_risiko_kerja.DESCP_RISIKO as RisikoKerja, mstr_ket_khusus.DESCP_KET as KetKhusus,
                                    mstr_intensitas.DESCP_INTENSITAS as IntensitasPasien, mstr_absensi.DESCP_ABSENSI as Kehadiran, mstr_pegawai.STATUS');
          $this->datatables->from('mstr_pegawai');
          //add this line for join
          //$this->datatables->join('table2', 'det_indeks_pegawai.field = table2.field');
          //$this->datatables->join('mstr_pegawai', 'indeks_pegawai.NIK = mstr_pegawai.NIK', 'LEFT');
          $this->datatables->join('mstr_level', 'mstr_pegawai.ID_LEVEL = mstr_level.ID_LEVEL', 'LEFT');
          $this->datatables->join('mstr_ruangan', 'mstr_pegawai.ID_RUANGAN = mstr_ruangan.ID_RUANGAN', 'LEFT');
          $this->datatables->join('mstr_karir', 'mstr_pegawai.ID_KARIR = mstr_karir.ID_KARIR', 'LEFT');
          $this->datatables->join('mstr_risiko_kerja', 'mstr_pegawai.ID_RISIKO = mstr_risiko_kerja.ID_RISIKO', 'LEFT');
          $this->datatables->join('mstr_ket_khusus', 'mstr_pegawai.ID_KET = mstr_ket_khusus.ID_KET', 'LEFT');
          $this->datatables->join('mstr_intensitas', 'mstr_pegawai.ID_INTENSITAS = mstr_intensitas.ID_INTENSITAS', 'LEFT');
          $this->datatables->join('mstr_absensi', 'mstr_pegawai.ID_ABSENSI = mstr_absensi.ID_ABSENSI', 'LEFT');

        //add this line for join
        //$this->datatables->join('table2', 'mstr_pegawai.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('pegawai/read/$1'),'Read')." | ".anchor(site_url('pegawai/update/$1'),'Update')." | ".anchor(site_url('pegawai/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'ID_PEGAWAI');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ID_PEGAWAI', $q);
	$this->db->or_like('NIK', $q);
	$this->db->or_like('NAMA_PEGAWAI', $q);
	$this->db->or_like('ID_LEVEL', $q);
	$this->db->or_like('ID_RUANGAN', $q);
	$this->db->or_like('ID_KARIR', $q);
	$this->db->or_like('ID_RISIKO', $q);
	$this->db->or_like('ID_KET', $q);
	$this->db->or_like('ID_INTENSITAS', $q);
	$this->db->or_like('ID_ABSENSI', $q);
	$this->db->or_like('STATUS', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID_PEGAWAI', $q);
	$this->db->or_like('NIK', $q);
	$this->db->or_like('NAMA_PEGAWAI', $q);
	$this->db->or_like('ID_LEVEL', $q);
	$this->db->or_like('ID_RUANGAN', $q);
	$this->db->or_like('ID_KARIR', $q);
	$this->db->or_like('ID_RISIKO', $q);
	$this->db->or_like('ID_KET', $q);
	$this->db->or_like('ID_INTENSITAS', $q);
	$this->db->or_like('ID_ABSENSI', $q);
	$this->db->or_like('STATUS', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_pegawai.php */
/* Location: ./application/models/M_pegawai.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-01 05:30:12 */
/* http://harviacode.com */
