<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_remunerasi extends CI_Model
{

    public $table = 'mstr_pegawai';
    public $id = 'ID_PEGAWAI';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('ID_PEGAWAI,NIK,NAMA_PEGAWAI,ID_LEVEL,ID_RUANGAN,ID_KARIR,ID_RISIKO,ID_KET,ID_INTENSITAS,ID_ABSENSI,ALAMAT,GENDER,TEMPAT_LAHIR,TGL_LAHIR,EMAIL,PHONE,STATUS');
        $this->datatables->from('mstr_pegawai');
        //add this line for join
        //$this->datatables->join('table2', 'mstr_pegawai.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('remunerasi/read/$1'),'Read')." | ".anchor(site_url('remunerasi/update/$1'),'Update')." | ".anchor(site_url('remunerasi/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'ID_PEGAWAI');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ID_PEGAWAI', $q);
	$this->db->or_like('NIK', $q);
	$this->db->or_like('NAMA_PEGAWAI', $q);
	$this->db->or_like('ID_LEVEL', $q);
	$this->db->or_like('ID_RUANGAN', $q);
	$this->db->or_like('ID_KARIR', $q);
	$this->db->or_like('ID_RISIKO', $q);
	$this->db->or_like('ID_KET', $q);
	$this->db->or_like('ID_INTENSITAS', $q);
	$this->db->or_like('ID_ABSENSI', $q);
	$this->db->or_like('ALAMAT', $q);
	$this->db->or_like('GENDER', $q);
	$this->db->or_like('TEMPAT_LAHIR', $q);
	$this->db->or_like('TGL_LAHIR', $q);
	$this->db->or_like('EMAIL', $q);
	$this->db->or_like('PHONE', $q);
	$this->db->or_like('STATUS', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID_PEGAWAI', $q);
	$this->db->or_like('NIK', $q);
	$this->db->or_like('NAMA_PEGAWAI', $q);
	$this->db->or_like('ID_LEVEL', $q);
	$this->db->or_like('ID_RUANGAN', $q);
	$this->db->or_like('ID_KARIR', $q);
	$this->db->or_like('ID_RISIKO', $q);
	$this->db->or_like('ID_KET', $q);
	$this->db->or_like('ID_INTENSITAS', $q);
	$this->db->or_like('ID_ABSENSI', $q);
	$this->db->or_like('ALAMAT', $q);
	$this->db->or_like('GENDER', $q);
	$this->db->or_like('TEMPAT_LAHIR', $q);
	$this->db->or_like('TGL_LAHIR', $q);
	$this->db->or_like('EMAIL', $q);
	$this->db->or_like('PHONE', $q);
	$this->db->or_like('STATUS', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_remunerasi.php */
/* Location: ./application/models/M_remunerasi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-26 17:36:21 */
/* http://harviacode.com */