<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_ruangan extends CI_Model
{

    public $table = 'mstr_ruangan';
    public $id = 'ID_RUANGAN';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('ID_RUANGAN,DESCP_RUANGAN');
        $this->datatables->from('mstr_ruangan');
        //add this line for join
        //$this->datatables->join('table2', 'mstr_ruangan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/ruangan/update/$1'),'<i class="fa fa-edit fa-lg" title="Edit" style="color:orange;">
         </i>')."&nbsp;&nbsp;&nbsp;&nbsp"
        .anchor(site_url('admin/ruangan/delete/$1'),'<i class="fa fa-trash fa-lg" title="Hapus" style="color:red;">
         </i>','onclick="javasciprt: return confirm(\'Hapus Data ini ?\')"'), 'ID_RUANGAN');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ID_RUANGAN', $q);
	$this->db->or_like('DESCP_RUANGAN', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID_RUANGAN', $q);
	$this->db->or_like('DESCP_RUANGAN', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_ruangan.php */
/* Location: ./application/models/M_ruangan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-27 06:25:52 */
/* http://harviacode.com */
